service: api-graphql

provider:
  name: aws
  runtime: nodejs8.10

functions:
  query:
    handler: handler.query
    events:
      - http:
          path: query
          method: post
          cors: true
      - http:
          path: playground
          method: get
          cors: true
          integration: lambda-proxy

plugins:
  - serverless-offline
